#!/usr/bin/env bash
# EC2 "user data" template.

echo "EC2BOX Update system packages"
apt-get -y update

echo "EC2BOX Install, configure and start CloudWatch Logs agent"
wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb &&
dpkg -i -E ./amazon-cloudwatch-agent.deb &&
tee ${awslogs} <<- EOF &&
{
  "agent": {
    "run_as_user": "${user}"
  },
  "logs": {
    "logs_collected": {
      "files": {
        "collect_list": [
          {
            "file_path": "/var/log/syslog",
            "log_group_name": "${name}",
            "log_stream_name": "{hostname}",
            "timezone": "UTC"
          }
        ]
      }
    }
  }
}
EOF
amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:${awslogs} -s

echo "EC2BOX Install extra software"
${install}

echo "EC2BOX Write ${script}"
cat > ${script} <<- EOF &&
${launch}
EOF
chown ${user} ${script} &&
chmod 700 ${script}

echo "EC2BOX Run ${script} in background as ${user}."
sudo --login --user ${user} bash -c '${script} 2>&1 | logger -t ${name} &'
