#!/usr/bin/env bash
# Cloud-init "user data" template.
# https://cloudinit.readthedocs.io/en/latest/

set -x

echo "EC2BOX Update system packages"
apt-get -y update

echo "EC2BOX Install, configure and start CloudWatch Logs agent"
wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb &&
dpkg -i -E ./amazon-cloudwatch-agent.deb &&
tee /etc/awslogs.json <<- EOF &&
{
  "agent": {
    "run_as_user": "${user}"
  },
  "logs": {
    "logs_collected": {
      "files": {
        "collect_list": [
          {
            "file_path": "/var/log/syslog",
            "log_group_name": "${name}",
            "log_stream_name": "{hostname}"
          }
        ]
      }
    }
  }
}
EOF
amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/etc/awslogs.json -s

echo "EC2BOX Install extra software"
${install}

echo "EC2BOX Write launch script"
cat > ${script} <<- EOF &&
${launch}
EOF
chown ${user} ${script} &&
chmod 700 ${script}

echo "EC2BOX Time's up. Let's do this."
sudo -u ${user} ${script}
