#!/usr/bin/env bash
# EC2 "user data" template.

echo "EC2BOX Update system packages"
apt-get -y update

echo "EC2BOX Install, configure and start CloudWatch Logs agent"
wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb &&
dpkg -i -E ./amazon-cloudwatch-agent.deb &&
tee ${folder}/awslogs.json <<- EOF &&
{
  "agent": {
    "run_as_user": "${user}"
  },
  "logs": {
    "logs_collected": {
      "files": {
        "collect_list": [
          {
            "file_path": "/var/log/syslog",
            "log_group_name": "${name}",
            "log_stream_name": "{hostname}",
            "timezone": "UTC"
          }
        ]
      }
    }
  }
}
EOF
amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:${folder}/awslogs.json -s

echo "EC2BOX Write and run install script"
cat > ${folder}/install <<- EOF &&
${file(install)}
EOF
chmod 700 ${folder}/install &&
${folder}/install

echo "EC2BOX Write and run launch script as ${user}"
cat > ${folder}/launch <<- EOF &&
${file(launch)}
EOF
chown ${user} ${folder}/launch &&
chmod 700 ${folder}/launch &&
sudo --login --user ${user} bash -c '${folder}/launch 2>&1 | logger -t ${name} &'
