#!/usr/bin/env bash
# Startup script for EC2 instance. Commands will be run as root!

echo 'EC2BOX Install security updates'
yum -y update

echo 'EC2BOX Install, configure, and start CloudWatch Logs'
yum -y install awslogs &&
tee /etc/awslogs/awslogs.conf <<- EOF &&
${awslogs}
EOF
systemctl enable --now awslogsd

echo "EC2BOX Run as ${ec2user}@$HOSTNAME"
cd /home/${ec2user}
su - ${ec2user}

echo "EC2BOX Time's up. Let's do this."
