#!/usr/bin/env bash
# Startup script for EC2 instance. Commands will be run as root!

set -ex
launch="/home/${ec2user}/launch"

echo 'EC2BOX Install any critical updates'
yum -y update

echo "EC2BOX Install, configure and start AWS logs daemon"
yum -y install awslogs
tee /etc/awslogs/awslogs.conf <<- EOF
${awslogs}
EOF
systemctl enable --now awslogsd

echo 'EC2BOX Install Ruby'
amazon-linux-extras install -y ruby2.6

echo "EC2BOX Write $launch"
cat > $launch <<- EOF
${script}
EOF

echo "EC2BOX Ensure ${ec2user} can run $launch"
chown ${ec2user} $launch
chmod 700 $launch

echo "EC2BOX Time's up. Let's do this."
sudo -u ${ec2user} $launch
